### ISSUE TITLE
Publish as npm @types package

### ISSUE THREAD

**Issue by Asone** [slockit/web3.ts#1]
Hi Simon,

As i'm building my own dApp with typescript and Angular, i was checking if someone already built the types interfaces for the Objects used and created with Web3.js and found your repo. 

First thing i have to say : **wow, congratz, nice work done here !** 

Second thing : As your work seems pretty complete at first sight, it would probably be useful for the community to have this package released for npmregistry as a @types package with a nice readme.md description. 

Pretty sure that many people would use this to help them have their objects sticking correctly to the types expected with web3js. I don't know if you plan to do this, however if that's the case i'd be glad to help in this. 

Much #datalove !

**Comment by mikeseese** [comment]
Sometime between Jan 20 and now, a @types package has been added to DefinitelyTyped. It has some bugs, but several people have been trying to improve it to match web3@1.0 functionality. Check it out: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/web3

Pretty sure those types heavily leveraged these types. Thanks @simon-jentzsch for all the great work! I do think this Issue can be closed, and personally, I think a note should be added to the README to link to the DefinitelyTyped package instead

**Comment by Asone** [comment]
Thanks for the information feedback @seesemichaelj ! I close the ticket
